### ISSUE TITLE
Error when embedding

### ISSUE THREAD

**Issue by tamizna** [VedantYadav/VQA#4]
I got error when embedding 

> D:\Downloads\VQA-master\VQA-master>python embedding.py -address D:\Downloads\VQA-master\VQA-master\embeddings\glove.840B.300d.txt
Preparing embeddings ...
Traceback (most recent call last):
  File "embedding.py", line 52, in <module>
    if __name__ == '__main__': main()
  File "embedding.py", line 50, in main
    create(args.address)
  File "embedding.py", line 26, in create
    for i, line in enumerate(f):
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 962: character maps to <undefined>

**Comment by VedantYadav** [comment]
Hello,
Do you have pre-train embedding matrix for glove/word2vec model already downloaded?
